url: http://127.0.0.1:8066

swagger_open: true

dev_fresh: 1

path:
  log_folder: "/Users/jiangbo/jiang/go_2021_dir/from0/gk02/storage/log/"
  runtime_folder: "/Users/jiangbo/jiang/go_2021_dir/from0/gk02/storage/runtime/"